class News {
  News({
    required this.title,
    required this.body,
    required this.image,
  });

  final String title;
  final String body;
  final String image;
}

List<News> newsList = [
  News(
    title:
        'Mystery as English Team\'s Soccer Ball Turns Up 400 Miles Away in Holland',
    body:
        'Nafferton Youth Football Club in East Yorkshire received a strange and offbeat message on Facebook from someone in Holland after one of their footballs washed ashore on the island of Terschelling, the team announced.\n\nThe Euro soccer competition kicks off this weekend in Germany and stars like Jude Bellingham, Harry Kane and Phil Foden will compete for the prize for England’s Three Lions. The celebrations have already begun for some fans of the sport, as a local team\'s long lost ball was finally found. It had managed to make its way 400 miles to Holland in a quirky mystery that\'s captivated many.\n\nNafferton Youth Football Club in East Yorkshire learned of the development through a message on Facebook from someone in Holland. The ball had washed ashore on the island of Terschelling, the team announced.\n\nIt\'s "one of life\'s mysteries," Sean Gibson, 42, chairman and coach at the club, told the BBC.\n\nSome have theorized that the soccer ball landed in a ditch and then washed down to the River Humber before eventually making it’s way out to sea and ending up in the Netherlands, the BBC reported.\n\nRenske Schroor, 51, found the ball while walking on a beach one morning, “We live in a street with young children, so we thought they would have a fun ball to play with," Schroor told Hull Live. "But when we got home we cleaned the ball and saw that it had the name of a football club on it. I decided to look on Facebook to see if I could find anything."\n\nSchroor found the name of the club written in marker on a part of the ball and contacted the team.\n\n"That was quickly found and the Nafferton youth football club immediately responded very enthusiastically to my message,” she told Hull Live.\n\nNafferton Youth Football Club took to Facebook to share the news that the ball was found and showcased images of it that Schroor sent.\n\n“It looks like shooting practice is in order at our next session,” the team wrote on Facebook.\n\nIt\'s not clear if the ball will return to England or stay in the Netherlands.',
    image:
        'https://www.insideedition.com/sites/default/files/images/2024-06/soccerball.jpg?crop=1170:658&width=1170',
  ),
  News(
    title: 'To be the first at anything is an unbelievable honour - Anderson',
    body:
        '“In the 1970s it was what you had to go through to survive - I just desperately wanted to be a professional footballer.”\n\nThe words of the first black man to play for the senior England team - Viv Anderson - have a steely, serious and thought-provoking undertone.\n\nMeeting and interviewing him was a cathartic experience for me - he was a black footballing trailblazer that every Caribbean household cherished.\n\nIt was the year of my birth, 1978, when Anderson walked out for England against Czechoslovakia at Wembley, taking his place in history.\n\n“To be the first at anything is an unbelievable honour - to be honest I don’t know where it comes from because my dad was always into cricket - I broke the mould there," Anderson recalled.\n\n“The Queen and Elton John sent me a telegram of congratulations - my mum and dad were interviewed all week - it was a big thing.”\n\nFor Anderson, it was all about the football. But almost unbeknown to him, his inclusion within the England team had ramifications that travelled far beyond the pitch.\n\nNot only did he help open the door for other talented black players to be considered for England, but for myself and many other families of British-Caribbean descent, he helped legitimise our place within wider society.\n\nThe former Nottingham Forest, Arsenal and Manchester United full-back was one of the first that we saw simultaneously represent England and ‘us’ on the field of play. It was an empowering moment of validation - a moment of feeling truly accepted.\n\n"I didn’t feel pressure, I just wanted to play football," Anderson, who went on to win 30 England caps, said.\n\nHe describes the moment he walked out on to the pitch.\n\n“It was a really unique experience, it was 100,000 [fans] - I could hear the crescendo getting louder and louder as I walked out, it was just an unbelievable experience not just for being black, but for playing for my country.”\n\nThe abhorrent racial abuse that Anderson faced from the terraces in the 1970s is very well documented.\n\nThe defender, who won the First Division with Forest in 1978, and the European Cup in 1979 and 1980, credits his parents and strong Jamaican upbringing for giving him the dignity and strength to overcome the hate.\n\n"My parents were part of the Windrush generation - it took my mother three weeks to come from the Caribbean on a boat," he said.\n\n"They didn’t have luxury cabins or any stuff like that, so what they went through is absolutely paramount to the way I was brought up and the way I conduct myself - it was always down to my parents."\n\nAnderson’s respect and gratitude for his parents and their guidance was clear for me to see. But despite deep-rooted challenges with racism, the game itself also played its part.',
    image:
        'https://ichef.bbci.co.uk/ace/standard/976/cpsprodpb/e31a/live/7ebd3d80-96ab-11ef-9260-19e6a950e830.jpg.webp',
  ),
  News(
    title:
        'Carabao Cup quarter-final draw: Tottenham host Man Utd while Liverpool go to Southampton',
    body:
        'Tottenham\'s reward for beating Manchester City is a quarter-final tie with Manchester United, while holders Liverpool go to Southampton.\n\nSpurs upset Pep Guardiola\'s Premier League champions 2-1 at the Tottenham Hotspur Stadium on Wednesday night and will now take on Manchester United, who thrashed Leicester City 5-2.\n\nInterim boss Ruud van Nistelrooy was in the dugout at Old Trafford for that win but Ruben Amorim could well be in charge by the time the quarter-final ties are played in the week commencing December 16.\n\nArsenal beat Preston 3-0 in their fourth-round tie to set up a last-eight date with Crystal Palace at the Emirates Stadium, while Newcastle knocked out last season\'s runners-up Chelsea at St James\' Park and will be at home again when they play Brentford for a spot in the semis.\n\n',
    image:
        'https://e0.365dm.com/24/10/1600x900/skysports-timo-werner-tottenham_6733615.jpg?20241030203257',
  ),
  News(
    title:
        'Hansi Flick\'s free-wheeling Barcelona have battered Bayern Munich and Real Madrid - there\'s no team playing better in Europe right now',
    body:
        'After yet another summer of uncertainty in Catalunya, the Blaugrana have somehow emerged as a fearsome force\n\nMonday\'s Ballon d\'Or ceremony was eerily similar to Saturday\'s Clasico: Real Madrid didn\'t turn up while Barcelona had a blast. The Catalan contingent were all smiles as they rocked up on the red carpet in Paris - and not just because they got to meet Hollywood star Natalie Portman.\n\nBarca Femeni occupied all three podium places in the women\'s Ballon d\'Or vote, with Aitana Bonmati taking top spot, while Lamine Yamal became the youngest male player ever to win The Kopa Trophy.\n\nMadrid, of course, were named Men\'s Club of the Year, while Carlo Ancelotti landed the Johan Cruyff Trophy for best men\'s coach of 2024 - but Los Blancos still end up looking like losers after petulantly boycotting the event simply because Rodri beat Vinicius Jr to the men\'s Ballon d\'Or.\n\nOne would have thought that Madrid would have had bigger concerns right now, given Hansi Flick\'s Barca have emerged as a serious threat to their hopes of retaining their Primera Division and Champions League titles...',
    image:
        'https://assets.goal.com/images/v3/blt3af4e96d731b9c36/Barca%20playing%20like%20the%20best%20team%20in%20Europe.jpg?auto=webp&format=pjpg&width=1080&quality=60',
  ),
  News(
    title:
        'Man Utd player ratings vs Leicester City: Van Nistelrooy\'s night to remember! Ruud\'s Red Devils run riot as Casemiro rolls back the years & Bruno Fernandes finds goal-scoring form in Carabao Cup clash',
    body:
        'United moved on from Erik ten Hag\'s sacking by flying into the League Cup quarter-finals as they saw off the Foxes\n\nIt doesn\'t sound like Ruud van Nistelrooy is in the frame to be given the Manchester United manager\'s job on a full-time basis, but the former striker made an ideal start to his interim tenure as he oversaw a 5-2 Carabao Cup win over Leicester City in the club\'s first game since the sacking of Erik ten Hag.\n\nAfter a relatively slow start, Casemiro got the goal-scoring under way as he powered a curling effort from 25 yards into the top corner. Alejandro Garnacho then doubled the Red Devils\' lead as he swept home Diogo Dalot\'s low ball across the edge of the penalty area.\n\nLeicester pulled one back when Bilal El Khannouss drilled a half-volley in off both posts, only for United to go up the other end and restore their two-goal lead when Bruno Fernandes netted his first of the season via a deflected free-kick. Casemiro soon added his second of the night with a close-range finish after his own header came back off both uprights, but there was still time in first-half stoppage-time for Conor Coady to get another one back for the visitors after Dalot failed to clear a free-kick into the box.\n\nPerhaps thinking the game was already won, United started the second half slowly and found themselves on the back foot until Fernandes latched onto Caleb Okoli\'s under-hit back-pass and rounded Danny Ward to ensure a relatively comfortable passage into the quarter-finals for the Red Devils.\n\nGOAL rates United\'s players from Old Trafford...',
    image:
        'https://assets.goal.com/images/v3/bltf06cb810172dd1b8/crop/MM5DCNRYGA5DSNBVHJXG653FHIYTINR2HA======/2_1%20(3).jpg?auto=webp&format=pjpg&width=1080&quality=60',
  ),
  News(
    title:
        'Liverpool player ratings vs Brighton: Cody Gakpo, the Carabao Cup king! Dutch star\'s double keeps up superb League Cup record and sends Reds to quarter-finals',
    body:
        'GOAL rates all of the Reds on show as the Dutchman helped himself to another two goals to see the champions through to the last eight\n\nJust call Cody Gakpo the King of the Carabao Cup! The Dutchman\'s double helped Liverpool kick-off their title defence with a 5-1 rout of West Ham at the tail end of September, and he bagged another brace in Wednesday\'s 3-2 fourth-round win at Brighton, meaning he now has eight goals in the competition since the start of last season.\n\nGakpo\'s 46th-minute opener at the Amex was a stunner, with the versatile winger cutting inside onto his favoured right foot before whipping the ball past Jason Steele from the left-hand side of the area. Gakpo struck again midway through the second half, this time rifling home after pouncing on some sloppy play from Tariq Lamptey.\n\nBrighton pulled a goal back with 10 minutes to go through Simon Adingra, but Arne Slot\'s side promptly restored their two-goal advantage thanks to Luis Diaz - which was just as well for the visitors, as Lamptey\'s deflected effort found its way past Vitezslav Jaros in the final minute.\n\nBelow, GOAL rates all of the Reds on show as the reigning champions progressed to the quarter-finals of the Carabao Cup...',
    image:
        'https://assets.goal.com/images/v3/bltdb7c65c4ec29224a/Cody%20Gakpo%20Liverpool%20HIC%202024-25.jpg?auto=webp&format=pjpg&width=1080&quality=60',
  ),
  News(
    title:
        'Why Man Utd want Ruben Amorim: The \'poet\' who had an internship with Jose Mourinho and turned Portuguese football on its head can give Red Devils the shake-up they need',
    body:
        'The 39-year-old has been on the radar of Europe\'s top clubs for some time and now looks set to land the toughest job of them all\n\nAny discussion about Portuguese football will quickly concern \'Os Tres Grandes\', the Big Three of Sporting CP, Porto and Benfica. Since the turn of the century, it had in reality narrowed to a Big Two. Sporting had ruled in the middle of the 20th Century, winning 10 league titles between 1941 and 1958, but Porto overtook them as Benfica\'s great rivals from the 1980s onwards, with Sporting winning no titles at all in the 1990s. They had a brief resurgence at the turn of the century, but then endured their longest drought of all time, with Benfica and Porto sharing the crown between them for 19 long years.\n\nThe lack of silverware was far from being the biggest problem, however. The atmosphere around the club had grown so toxic that in 2018, a mob of 50 masked fans invaded the dressing rooms at the club\'s training ground and started attacking the players, shouting: "We\'re going to kill you." The assault led to seven players cancelling their contracts, including Portugal internationals Rui Patricio and William Carvalho as well as top prospect Rafael Leao, and to president Bruno de Carvalho being voted out by members.\n\nBut just three years on from the darkest day in the club\'s history, Sporting ended Porto and Benfica\'s near two-decade stranglehold on the title, lifting the 2021 title. And the architect of this historic turnaround was Ruben Amorim, the man Manchester United have chosen to replace Erik ten Hag.\n\nAmorim\'s achievements did not end with that title win. He took the team to the knockout stages of the Champions League for the first time in 11 years and then to the quarter-finals of the Europa League. And last season, Sporting reclaimed their crown, winning their 20th title with two games to spare. They have gone from strength to strength, winning all nine of their league games so far this term while taking seven points from their three matches in the Champions League.\n\nAmorim has put the meaning back in the notion of the \'Big Three\' and Sporting are back to where they believe they should be, as the pre-eminent force in Portuguese football after a long period in the wilderness. So it is not surprising that United have turned to the 39-year-old after making an abysmal start to the season. But will Amorim be able to succeed where so many of his prestigious predecessors have failed?\n\n',
    image:
        'https://assets.goal.com/images/v3/blt728102a44b60f66c/Who%20is%20Man%20Utd%20target%20Ruben%20Amorim_.jpg?auto=webp&format=pjpg&width=1080&quality=60',
  ),
  News(
    title: 'How Premier League helps grassroots football in China',
    body:
        'Premier Skills programme with British Council has been developing the game in China for 15 years\n\nTo mark the opening of its first international office in Beijing, the Premier League delivered a grassroots coach development course for 35 community football coaches from different regions in China.\n\nLed by Premier League coaches from Leicester City, Manchester United, Tottenham Hotspur and Wolverhampton Wanderers, the four-day course provided theory and practical training to equip coaches with the confidence and skills to deliver football sessions in their provinces.\n\nAlso in attendance on the third day were Premier League legends Michael Owen and Nemanja Vidic, who saw the coaches put their training into action with 80 local schoolchildren and provided their own tips and advice to the grateful coaches.\n\nOwen and Vidic were joined on Thursday by ex-Manchester City and China player Sun Jihai at an event in the Workers\' Stadium, Beijing, to celebrate Premier Skills, which the UK Ambassador to China also attended.\n\nLong-term support for Chinese game\n\nThe Premier League has been supporting grassroots football in China for 15 years. Working in partnership with the British Council since 2009, the League has delivered the Premier Skills coaching programme in 28 cities, providing training to more than 6,300 grassroots coaches, referees and teachers in China.\n\nTwo of the community football coaches who attended this week’s event shared how Premier Skills has helped them over the past seven years or so.',
    image:
        'https://resources.premierleague.pulselive.com/photo-resources/2024/10/17/caa7f403-8ed2-4ba5-87f0-9283ad9f6839/Premier-League-legends-and-UK-Ambassador-attend-Premier-Skills-Showcase-Beijing.JPG?width=1400&height=800',
  ),
  News(
    title: '"Amorim is a serial rebuilder and a developer of young players"',
    body:
        'European football expert Andy Brassell explains why Sporting\'s head coach is in demand\n\nRuben Amorim\'s formative experiences as a manager included an internship under Jose Mourinho at Manchester United. Now, six years later, he could become the club\'s new head coach. Here, European football expert Andy Brassell looks at the 39-year-old’s credentials and career so far.\n\nThe spotlight is firmly on Ruben Amorim as Manchester United look for their new head coach, and if he were to be appointed then a hugely challenging task lies ahead of him. Fortunately, he is no stranger to the most intense of pressures.\n\nWhen Sporting Lisbon paid Braga a reported €10million in compensation for Amorim in March 2020 it was an enormous risk for them. The former Benfica player had won the Taaa da Liga, the country\'s League Cup, for Braga but had only taken charge of 13 matches.\n\nSporting, without huge resources, were going all-in on their coach and then some.\n\nWhen he arrived at Estadio Jose Alvalade, he was inheriting a big-name team struggling badly to match expectations.\n\nThe fact is that Amorim has not just paid that faith back but wildly overachieved since then. In 2020/21 he led Sporting to a first league title in 19 years - they had a teenage Cristiano Ronaldo in the team for their previous triumph - and has rebuilt the squad, despite a raft of losses.\n\nAmorim’s midfield was decimated when Joao Palhinha and Matheus Nunes left for successful careers in the Premier League, and he later saw Pedro Porro join Tottenham Hotspur, while Paris Saint-Germain picked off key players Nuno Mendes and Manuel Ugarte.\n\nDespite having lesser resources than city rivals Benfica – the traditional giants of the Portuguese game – Amorim has managed to make Sporting competitive through his tenure in charge.\n\nThat, in a nutshell, is why Man Utd have made an approach to hire him. He is the right person at the right time for this job, a serial rebuilder and an encourager and developer of young players.',
    image:
        'https://resources.premierleague.pulselive.com/photo-resources/2024/10/30/5239b4cd-8ecf-47fb-b60e-dcd6ffcc5011/GettyImages-2179039032.jpg?width=1400&height=800',
  ),
  News(
    title:
        'Carabao Cup quarter-final draw: Tottenham take on Man Utd in all-Premier League last eight',
    body:
        'Tottenham welcome Manchester United in the Carabao Cup quarter-finals in an all-Premier League last eight.\n\nIn the other ties Crystal Palace will travel to the Emirates to take on Arsenal while Newcastle and Southampton will play at home against Brentford and Liverpool respectively.\n\nCarabao Cup last-16 round-up\n\nTimo Werner’s first goal in 18 matches and Pape Sarr’s curler saw Tottenham knock Manchester City out of the Carabao Cup with a 2-1 win.\n\nWerner set Spurs on course for victory when he rifled home in the fifth minute, which was followed by Sarr’s stunner midway through the first half.\n\nCity responded with a Matheus Nunes goal on the stroke of half-time but Tottenham held on to reach the quarter-finals.\n\nInterim boss Ruud van Nistelrooy’s Manchester United roared to an entertaining 5-2 victory against Leicester as the post-Erik ten Hag era began with a bang.\n\nUnited are in talks to hire Sporting Lisbon boss Ruben Amorim but appear to be safe in hands should negotiations drag on.\n\nCasemiro opened the scoring with a superb long-range strike and Alejandro Garnacho grabbed another before Bilal El Khannouss pulled one back for Leicester.\n\nUnited hit back through a deflected Bruno Fernandes free-kick and Casemiro’s second of the night.\n\nConor Coady cut the lead in first-half stoppage time, but Fernandes coolly scored his second on an evening when fan favourite Van Nistelrooy’s name frequently filled the air.\n\nA quickfire first-half double saw Newcastle earn revenge over Chelsea with a 2-0 win.\n\nThree days on from their Premier League defeat to the Blues at Stamford Bridge, Newcastle scored twice in the space of three minutes when Alexander Isak pounced on a mistake at the back to net the opener.\n\nThey quickly doubled their lead when Joe Willock’s deflected header was turned in to his own net by Axel Disasi.\n\nCody Gakpo claimed a stunning second-half double as holders Liverpool progressed with a 3-2 win at Brighton.\n\nSimon Adingra poked home on the rebound 10 minutes from time to halve the deficit before Luis Diaz quickly restored the two-goal cushion for Arne Slot’s side, prior to Tariq Lamptey’s deflected consolation.',
    image:
        'https://images.ps-aws.com/c?url=https%3A%2F%2Fd2x51gyc4ptf2q.cloudfront.net%2Fcontent%2Fuploads%2F2022%2F08%2F23181518%2Fcarabao-cup.jpg',
  ),
  // News(
  //   title: '',
  //   body: '',
  //   image: '',
  // ),
];
